config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    # ログイン及びログアウト
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#sign_out"
    delete "sign_out", to: "users/sessions#destroy"

    # 新規登録画面
    get "sign_up/top", to: "users/registrations#top"
    get "sign_up", to: "users/registrations#new"
    post "sign_up", to: "users/registrations#create"
    get "sign_up/sms_authorization", to: "users/registrations#sms_authorization"
    get "sign_up/deliver_address", to: "users/registrations#deliver_address"
    post "sign_up/deliver_address", to: "users/registrations#deliver_address_create"
    get "sign_up/credit_card", to: "users/registrations#credit_card"
    get "sign_up/finish", to: "users/registrations#finish"
  end

  # 商品画面
  resources :items, only: [:index, :new, :edit, :update, :show, :destroy, :create] do   # createは消す # 商品出品とコンフリクトするかも
    post "likes", to: "item_likes#create"
    delete "likes", to: "item_likes#destroy"
    resources :trades, only: [:new, :create]
    member do
      get :mypage_item_show   # マイページから出品した商品の詳細を表示するためのルーティング
    end
  end

  resources :users, only: [:show, :create] do
    # クレジットカード
    resource :credit_card, except: [:edit, :update], module: :users
    # お届け先住所
    resource :deliver_address, except: [:edit, :destroy], module: :users
    
    member do
      get :profile
      get :identification

      scope 'listings', module: :users, controller: 'listings' do
        get :listing
        get :in_progress
        get :completed
      end
    end
  end

  # カテゴリ
  resources :categories, only: [:index, :show]
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :sns_credentials, dependent: :destroy
  has_many :items
  has_many :item_likes
  has_many :liked_items, through: :item_likes, source: :item
  has_many :user_reviews
  has_one :credit_card
  has_one :deliver_address
  has_many :comments, dependent: :destroy

  validates_with UserValidator

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first

    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
      unless user.present?
        user = User.new(nickname: auth.info.name, email: auth.info.email)
      end
      sns = snscredential
    else
      user = User.where(email: auth.info.email).first
      if user.present?
        sns = SnsCredential.new(uid: uid, provider: provider, user_id: user.id)
      else
        user = User.new(nickname: auth.info.name, email: auth.info.email)
        sns = SnsCredential.new(uid: uid, provider: provider)
      end
    end
    return { user: user , sns: sns }
  end

  def good_count
    user_reviews.good_score.count
  end

  def normal_count
    user_reviews.normal_score.count
  end

  def bad_count
    user_reviews.bad_score.count
  end

  def full_name
    "#{last_name}#{first_name}"
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/credit_cards_controller.rb
class Users::CreditCardsController < ApplicationController
  require "payjp"

  before_action :set_credit_card, only: [:show, :new, :destroy]
  before_action :set_PAYJP_PRIVATE_KEY, only: [:show, :create, :destroy]

  def show
    if @credit_card.present?
      customer = Payjp::Customer.retrieve(@credit_card.customer_id)
      @default_card_information = customer.cards.retrieve(@credit_card.card_id)
      set_card_limit
      set_brand_icon
    end
  end

  def new
    redirect_to action: "show" if @credit_card.present?
  end

  def create
    # payjpの顧客データを作成
    if params['payjp_token'].present?
      customer = Payjp::Customer.create(
        card: params['payjp_token'],
        metadata: {user_id: current_user.id}
      )
      # credit_cardsテーブルにレコードを保存
      @credit_card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @credit_card.save
        redirect_to action: "show"
      else
        redirect_to action: "create"
      end
    else
      redirect_to action: "new"
    end
  end

  def destroy
    if @credit_card.present?
      customer = Payjp::Customer.retrieve(@credit_card.customer_id)
      customer.delete
      @credit_card.delete
    end
    redirect_to action: "show"
  end

  private
  # payjp秘密鍵を取得
  def set_PAYJP_PRIVATE_KEY
    Payjp.api_key = Rails.application.credentials.payjp[:private_key]
  end

  # クレジットカード情報を取得
  def set_credit_card
    @credit_card = CreditCard.find_by(user_id: current_user.id)
  end

  # 使用期限を取得
  def set_card_limit
    exp_month = @default_card_information.exp_month.to_s
    exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    @card_limit = exp_month + " / " + exp_year
  end

  # カードブランドのアイコンを取得
  def set_brand_icon
    @card_brand = @default_card_information.brand
      case @card_brand
        when "Visa"
          @brand_icon = "/visa.svg"
        when "JCB"
          @brand_icon = "/jcb.svg"
        when "MasterCard"
          @brand_icon = "/master-card.svg"
        when "American Express"
          @brand_icon = "/american_express.svg"
        when "Diners Club"
          @brand_icon = "/dinersclub.svg"
        when "Discover"
          @brand_icon = "/discover.svg"
      end
  end

end

app/controllers/users/deliver_addresses_controller.rb
class Users::DeliverAddressesController < ApplicationController

  def show
    @deliver_address = current_user.deliver_address ? current_user.deliver_address : DeliverAddress.new
  end

  def new
    @deliver_address = DeliverAddress.new
  end

  def create
    @deliver_address = DeliverAddress.new(deliver_address_params)
    if @deliver_address.save
      redirect_to action: "show"
    else
      render :show
    end
  end

  def update
    @deliver_address = current_user.deliver_address
    if @deliver_address.update(deliver_address_params)
      redirect_to action: "show"
    else
      render :show
    end
  end

  private

  def deliver_address_params
    params.require(:deliver_address).permit(
      :first_name,
      :last_name,
      :first_name_kana,
      :last_name_kana,
      :zipcode,
      :prefecture_id,
      :city,
      :house_address,
      :building_name,
      :phone_number
    ).merge(user_id: current_user.id)
  end
end

app/controllers/users/listings_controller.rb
class Users::ListingsController < ApplicationController
  def listing
    @items = current_user.items.includes(:item_images).recently.where(task: :exhibiting)
  end

  def in_progress
    @items = current_user.items.includes(:item_images).recently.where(task: [:waiting_shipping, :rating_seller, :rating_buyer])
    render :listing
  end

  def completed
    @items = current_user.items.includes(:item_images).recently.where(task: :complete)
    render :listing
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    set_user_and_sns_id
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      render template: "users/registrations/new"
      session[:sns] = @sns
    end
  end

  def failure
    redirect_to root_path and return
  end

  private

  def set_user_and_sns_id
    info = User.find_oauth(request.env["omniauth.auth"])
    @user = info[:user]
    @sns = info[:sns]
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    if session[:sns]
      set_password
      super
      create_sns_credential
    else
      super
    end
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  def top
    redirect_to root_url if user_signed_in?
  end

  def sms_authorization
    @user = User.new
  end

  def deliver_address
    @deliver_address = DeliverAddress.new
  end

  def deliver_address_create
    # 本当はdeliver_addressのコントローラでやりたいが、現状は仕方なく
    @deliver_address = DeliverAddress.new(deliver_address_params)
    if @deliver_address.save
      redirect_to action: "credit_card"
    else
      render :deliver_address
    end
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    change_to_kana
    devise_parameter_sanitizer.permit(
      :sign_up,
      keys: [:nickname,
             :email,
             :password,
             :password_confirmation,
             :first_name,
             :first_name_kana,
             :last_name,
             :last_name_kana,
             :birth_date])
  end

  private

  def change_to_kana
    first_name_kana = params[:user][:first_name_kana]
    last_name_kana = params[:user][:last_name_kana]
    params[:user][:first_name_kana] = first_name_kana.tr('ぁ-ん','ァ-ン')
    params[:user][:last_name_kana] = last_name_kana.tr('ぁ-ん','ァ-ン')
  end

  def set_password
    password = Devise.friendly_token.first(14)
    password.insert(rand(14), rand(9).to_s).insert(rand(15), ("A".."Z").to_a[rand(26)])
    params[:user][:password] = password
    params[:user][:password_confirmation] = password
  end

  def create_sns_credential
    sns = session[:sns]
    session[:sns] = nil
    sns[:user_id] = @user.id
    SnsCredential.create(sns)
  end

  def deliver_address_params
    params.require(:deliver_address).permit(
      :first_name,
      :last_name,
      :first_name_kana,
      :last_name_kana,
      :zipcode,
      :prefecture_id,
      :city,
      :house_address,
      :building_name,
      :phone_number
    ).merge(user_id: current_user.id)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper

  # 使用期限の選択肢(year)
  def limit_y
    years = []
    (Time.current.year..Time.current.year+10).each do |year|
      years << (year % 100).to_s
    end
    years
  end

  # 使用期限の選択肢(month)
  def limit_m
    (1..12).map do |month|
      if month < 10
        "0#{month}"
      else
        "#{month}"
      end
    end
  end

end

app/views/users/credit_cards/new.html.haml
- breadcrumb :credit_card
= render 'items/header_guide'
= render 'shared/breadcrumbs'
%main.mypage-container.clearfix

  .content
    %section.registration-card
      %h2.registration-card__head.bold
        クレジットカード情報入力

      = form_with url: user_credit_card_path, method: :post, class: 'registration-card__form', id: 'registration-card__form' do |f|
        .registration-card__form__content

          .registration-card__form__content__number
            = f.label "カード番号", class: "bold"
            %span.form-require 必須
            = f.text_field :card_number, {placeholder: "半角数字のみ", maxlength: "19", data: {type: 'card'}}
            %ul.card-images
              %li
                = image_tag '/visa.svg', height: '20', width: '49', class: 'card-images__image'
              %li
                = image_tag '/master-card.svg', height: '20', width: '34', class: 'card-images__image'
              %li
                = image_tag '/saison-card.svg', height: '20', width: '30', class: 'card-images__image'
              %li
                = image_tag '/jcb.svg', height: '20', width: '32', class: 'card-images__image'
              %li
                = image_tag '/american_express.svg', height: '20', width: '21', class: 'card-images__image'
              %li
                = image_tag '/dinersclub.svg', height: '20', width: '32', class: 'card-images__image'
              %li
                = image_tag '/discover.svg', height: '20', width: '32', class: 'card-images__image'

          .registration-card__form__content__limit
            = f.label "有効期限", class: "bold"
            %span.form-require 必須
            %br
            .select.half
              = f.select :card_limit_m, options_for_select(limit_m)
              %i.icon-arrow-bottom
              %span 月
            .select.half
              = f.select :card_limit_y, options_for_select(limit_y)
              %i.icon-arrow-bottom
              %span 年

          .registration-card__form__content__securitycode
            = f.label "セキュリテイコード", class: "bold"
            %span.form-require 必須
            = f.text_field :card_securitycode, {placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4"}
            .what-is-securitycode
              %span ?
              カード裏面の番号とは？

          #card_token
          = f.button "追加する", class: 'registration-card__form__content__submit', id: 'registration-card__form__content__submit'

  = render 'users/mypage/side'
  = render 'items/footer_btn'

= render 'items/footer'

app/views/users/credit_cards/show.html.haml
- breadcrumb :credit_card
= render 'items/header_guide'
= render 'shared/breadcrumbs'
%main.mypage-container.clearfix

  .content
    %section.registration-card
      %h2.registration-card__head.bold
        支払い方法

      .registration-card__body
        .registration-card__body__upper
          %h3.registration-card__body__upper__head.bold
            クレジットカード一覧
          %ul.registration-card__body__upper__list
            %li.registrated-card

        .registration-card__body__inner
          - if @default_card_information.present?
            %ul
              %li
                = form_with url: user_credit_card_path, method: :delete do |f|
                  = f.text_field :user_id, {type: "hidden", value: "#{@credit_card.user_id}"}
                  = f.button "削除する", class: 'registration-card__body__inner__delete'
                  %figure
                    = image_tag @brand_icon, height: '20', width: '29', class: 'brand-icon'
                  .registration-card__body__inner__card-info
                    = "************ " + @default_card_information.last4
                  .registration-card__body__inner__card-info
                    = @card_limit
          - else
            .registration-card__body__inner__add-card
              .registration-card__body__inner__add-card__btn
                = link_to new_user_credit_card_path do
                  %i.icon-card
                  クレジットカードを追加する

        .registration-card__body__lower
          = link_to root_path, traget: "_blank" do
            %span 支払い方法について
            %i.icon-right-arrow

  = render 'users/mypage/side'
  = render 'items/footer_btn'

= render 'items/footer'