config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    # ログイン及びログアウト
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#sign_out"
    delete "sign_out", to: "users/sessions#destroy"

    # 新規登録画面
    get "sign_up/top", to: "users/registrations#top"
    get "sign_up", to: "users/registrations#new"
    post "sign_up", to: "users/registrations#create"
    get "sign_up/sms_authorization", to: "users/registrations#sms_authorization"
    get "sign_up/deliver_address", to: "users/registrations#deliver_address"
    post "sign_up/deliver_address", to: "users/registrations#deliver_address_create"
    get "sign_up/credit_card", to: "users/registrations#credit_card"
    get "sign_up/finish", to: "users/registrations#finish"
  end

  # 商品画面
  resources :items, only: [:index, :new, :edit, :update, :show, :destroy, :create] do   # createは消す # 商品出品とコンフリクトするかも
    post "likes", to: "item_likes#create"
    delete "likes", to: "item_likes#destroy"
    resources :trades, only: [:new, :create]
    member do
      get :mypage_item_show   # マイページから出品した商品の詳細を表示するためのルーティング
    end
  end

  resources :users, only: [:show, :create] do
    # クレジットカード
    resource :credit_card, except: [:edit, :update], module: :users
    # お届け先住所
    resource :deliver_address, except: [:edit, :destroy], module: :users
    
    member do
      get :profile
      get :identification

      scope 'listings', module: :users, controller: 'listings' do
        get :listing
        get :in_progress
        get :completed
      end
    end
  end

  # カテゴリ
  resources :categories, only: [:index, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :sns_credentials, dependent: :destroy
  has_many :items
  has_many :item_likes
  has_many :liked_items, through: :item_likes, source: :item
  has_many :user_reviews
  has_one :credit_card
  has_one :deliver_address
  has_many :comments, dependent: :destroy

  validates_with UserValidator

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first

    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
      unless user.present?
        user = User.new(nickname: auth.info.name, email: auth.info.email)
      end
      sns = snscredential
    else
      user = User.where(email: auth.info.email).first
      if user.present?
        sns = SnsCredential.new(uid: uid, provider: provider, user_id: user.id)
      else
        user = User.new(nickname: auth.info.name, email: auth.info.email)
        sns = SnsCredential.new(uid: uid, provider: provider)
      end
    end
    return { user: user , sns: sns }
  end

  def good_count
    user_reviews.good_score.count
  end

  def normal_count
    user_reviews.normal_score.count
  end

  def bad_count
    user_reviews.bad_score.count
  end

  def full_name
    "#{last_name}#{first_name}"
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/credit_cards_controller.rb
class Users::CreditCardsController < ApplicationController
  require "payjp"

  before_action :set_credit_card, only: [:show, :new, :destroy]
  before_action :set_PAYJP_PRIVATE_KEY, only: [:show, :create, :destroy]

  def show
    if @credit_card.present?
      customer = Payjp::Customer.retrieve(@credit_card.customer_id)
      @default_card_information = customer.cards.retrieve(@credit_card.card_id)
      set_card_limit
      set_brand_icon
    end
  end

  def new
    redirect_to action: "show" if @credit_card.present?
  end

  def create
    # payjpの顧客データを作成
    if params['payjp_token'].present?
      customer = Payjp::Customer.create(
        card: params['payjp_token'],
        metadata: {user_id: current_user.id}
      )
      # credit_cardsテーブルにレコードを保存
      @credit_card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @credit_card.save
        redirect_to action: "show"
      else
        redirect_to action: "create"
      end
    else
      redirect_to action: "new"
    end
  end

  def destroy
    if @credit_card.present?
      customer = Payjp::Customer.retrieve(@credit_card.customer_id)
      customer.delete
      @credit_card.delete
    end
    redirect_to action: "show"
  end

  private
  # payjp秘密鍵を取得
  def set_PAYJP_PRIVATE_KEY
    Payjp.api_key = Rails.application.credentials.payjp[:private_key]
  end

  # クレジットカード情報を取得
  def set_credit_card
    @credit_card = CreditCard.find_by(user_id: current_user.id)
  end

  # 使用期限を取得
  def set_card_limit
    exp_month = @default_card_information.exp_month.to_s
    exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    @card_limit = exp_month + " / " + exp_year
  end

  # カードブランドのアイコンを取得
  def set_brand_icon
    @card_brand = @default_card_information.brand
      case @card_brand
        when "Visa"
          @brand_icon = "/visa.svg"
        when "JCB"
          @brand_icon = "/jcb.svg"
        when "MasterCard"
          @brand_icon = "/master-card.svg"
        when "American Express"
          @brand_icon = "/american_express.svg"
        when "Diners Club"
          @brand_icon = "/dinersclub.svg"
        when "Discover"
          @brand_icon = "/discover.svg"
      end
  end

end

app/controllers/users/deliver_addresses_controller.rb
class Users::DeliverAddressesController < ApplicationController

  def show
    @deliver_address = current_user.deliver_address ? current_user.deliver_address : DeliverAddress.new
  end

  def new
    @deliver_address = DeliverAddress.new
  end

  def create
    @deliver_address = DeliverAddress.new(deliver_address_params)
    if @deliver_address.save
      redirect_to action: "show"
    else
      render :show
    end
  end

  def update
    @deliver_address = current_user.deliver_address
    if @deliver_address.update(deliver_address_params)
      redirect_to action: "show"
    else
      render :show
    end
  end

  private

  def deliver_address_params
    params.require(:deliver_address).permit(
      :first_name,
      :last_name,
      :first_name_kana,
      :last_name_kana,
      :zipcode,
      :prefecture_id,
      :city,
      :house_address,
      :building_name,
      :phone_number
    ).merge(user_id: current_user.id)
  end
end

app/controllers/users/listings_controller.rb
class Users::ListingsController < ApplicationController
  def listing
    @items = current_user.items.includes(:item_images).recently.where(task: :exhibiting)
  end

  def in_progress
    @items = current_user.items.includes(:item_images).recently.where(task: [:waiting_shipping, :rating_seller, :rating_buyer])
    render :listing
  end

  def completed
    @items = current_user.items.includes(:item_images).recently.where(task: :complete)
    render :listing
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    set_user_and_sns_id
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      render template: "users/registrations/new"
      session[:sns] = @sns
    end
  end

  def failure
    redirect_to root_path and return
  end

  private

  def set_user_and_sns_id
    info = User.find_oauth(request.env["omniauth.auth"])
    @user = info[:user]
    @sns = info[:sns]
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    if session[:sns]
      set_password
      super
      create_sns_credential
    else
      super
    end
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  def top
    redirect_to root_url if user_signed_in?
  end

  def sms_authorization
    @user = User.new
  end

  def deliver_address
    @deliver_address = DeliverAddress.new
  end

  def deliver_address_create
    # 本当はdeliver_addressのコントローラでやりたいが、現状は仕方なく
    @deliver_address = DeliverAddress.new(deliver_address_params)
    if @deliver_address.save
      redirect_to action: "credit_card"
    else
      render :deliver_address
    end
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    change_to_kana
    devise_parameter_sanitizer.permit(
      :sign_up,
      keys: [:nickname,
             :email,
             :password,
             :password_confirmation,
             :first_name,
             :first_name_kana,
             :last_name,
             :last_name_kana,
             :birth_date])
  end

  private

  def change_to_kana
    first_name_kana = params[:user][:first_name_kana]
    last_name_kana = params[:user][:last_name_kana]
    params[:user][:first_name_kana] = first_name_kana.tr('ぁ-ん','ァ-ン')
    params[:user][:last_name_kana] = last_name_kana.tr('ぁ-ん','ァ-ン')
  end

  def set_password
    password = Devise.friendly_token.first(14)
    password.insert(rand(14), rand(9).to_s).insert(rand(15), ("A".."Z").to_a[rand(26)])
    params[:user][:password] = password
    params[:user][:password_confirmation] = password
  end

  def create_sns_credential
    sns = session[:sns]
    session[:sns] = nil
    sns[:user_id] = @user.id
    SnsCredential.create(sns)
  end

  def deliver_address_params
    params.require(:deliver_address).permit(
      :first_name,
      :last_name,
      :first_name_kana,
      :last_name_kana,
      :zipcode,
      :prefecture_id,
      :city,
      :house_address,
      :building_name,
      :phone_number
    ).merge(user_id: current_user.id)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/views/users/_profile_edit.html.haml
%main.mypage-container.clearfix
  = render 'users/mypage/side'

  .profile
    .profile__contener
      %h2 プロフィール
    = form_with url: '#', class: 'profile__greeting' do |f|
      .profile__greeting  
        .profile__greeting__icon
          %figure
            = image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbM5lmk9ySlH6e3nKSxCUsmKEkIxPwsPIFuvDikBpe-I2pSSNQ")
          = f.text_field :nickname ,value:"テックエキスパー子", placeholder:"(例)AYA★セール中", class:"input-box"

      .profile__sentence
        = f.text_area :introduction,placeholder: "例）こんにちは☆ テックエキスパー子です！ピンク中心に出品しています。楽しくプログラミングできるように心がけています。お気軽にどうぞ♪"

        .profile__sentence__change_content
          = button_tag "変更する",type: 'submit', class: 'btn-default'

app/views/users/_user.html.haml
.detail-user

  .detail-user__header
    = link_to user_path(@user) do
      .detail-user__header__avatar
        = image_tag '/sample-avatar.jpg'
      .detail-user__header__name
        %span=@user.nickname
    .detail-user__header__info
      %span="評価 #{user.user_reviews.count}"
      %span="出品数 #{user.items.count}"

  .detail-user__ratings
    .detail-user__ratings__box
      %svg.icon-good.svg-inline--fa.fa-laugh.fa-w-16{width: '24px', height: '24px', "aria-hidden": "true", "data-icon": "laugh", "data-prefix": "fas", focusable: "false", role: "img", viewbox: "0 0 496 512", xmlns: "http://www.w3.org/2000/svg"}
        %path{d: "M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm80 152c17.7 0 32 14.3 32 32s-14.3 32-32 32-32-14.3-32-32 14.3-32 32-32zm-160 0c17.7 0 32 14.3 32 32s-14.3 32-32 32-32-14.3-32-32 14.3-32 32-32zm88 272h-16c-73.4 0-134-55-142.9-126-1.2-9.5 6.3-18 15.9-18h270c9.6 0 17.1 8.4 15.9 18-8.9 71-69.5 126-142.9 126z", fill: "currentColor"}
      %span.detail-user__ratings__box--text=user.good_count

    .detail-user__ratings__box
      %svg.icon-normal.svg-inline--fa.fa-meh.fa-w-16{width: '24px', height: '24px', "aria-hidden": "true", "data-icon": "meh", "data-prefix": "fas", focusable: "false", role: "img", viewbox: "0 0 496 512", xmlns: "http://www.w3.org/2000/svg"}
        %path{d: "M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm-80 168c17.7 0 32 14.3 32 32s-14.3 32-32 32-32-14.3-32-32 14.3-32 32-32zm176 192H152c-21.2 0-21.2-32 0-32h192c21.2 0 21.2 32 0 32zm-16-128c-17.7 0-32-14.3-32-32s14.3-32 32-32 32 14.3 32 32-14.3 32-32 32z", fill: "currentColor"}
      %span.detail-user__ratings__box--text=user.normal_count

    .detail-user__ratings__box
      %svg.icon-bad.svg-inline--fa.fa-frown.fa-w-16{width: '24px', height: '24px', "aria-hidden": "true", "data-icon": "frown", "data-prefix": "fas", focusable: "false", role: "img", viewbox: "0 0 496 512", xmlns: "http://www.w3.org/2000/svg"}
        %path{d: "M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm80 168c17.7 0 32 14.3 32 32s-14.3 32-32 32-32-14.3-32-32 14.3-32 32-32zm-160 0c17.7 0 32 14.3 32 32s-14.3 32-32 32-32-14.3-32-32 14.3-32 32-32zm170.2 218.2C315.8 367.4 282.9 352 248 352s-67.8 15.4-90.2 42.2c-13.5 16.3-38.1-4.2-24.6-20.5C161.7 339.6 203.6 320 248 320s86.3 19.6 114.7 53.8c13.6 16.2-11 36.7-24.5 20.4z", fill: "currentColor"}
      %span.detail-user__ratings__box--text=user.bad_count

  .detail-user__description
    .detail-user__description__text
      %span=user.description

  .detail-user__sns
    .detail-user__sns--facebook
      = facebook_link(@user)

    .detail-user__sns--twitter
      = twitter_link(@user)

  .detail-user__items
    %h2.detail-user__items__title="この出品者の商品"
    .detail-user__items__contents
      - @user.items.includes(:item_images).recently.each do |item|
        .detail-user__items__content
          = link_to item_path(item), nil do
            - if item.task.include?('complete')
              = render 'shared/soldout'
            %figure.detail-user__items__content--figure
              - if item.item_images.present?
                = image_tag item.item_images.first.image.url, class: "lazyloaded"
              - else
                = image_tag('/not_found.png')
            .detail-user__items__content__box
              %h3.detail-user__items__content__box--title.font-2=item.name
              .detail-user__items__content__box--footer
                .detail-user__items__content__box--price.font-5="¥#{item.delimited_price}"
                .detail-user__items__content__box--like.font-2
                  %i.icon-like
                  %span=item.item_likes.count

app/views/users/identification.html.haml
- breadcrumb :identification
= render 'items/header_guide'
= render 'shared/breadcrumbs'
%main.mypage-container.clearfix

  = render 'users/mypage/side'

  %section.identification
    %h2.identification__head
      本人情報の登録
    = form_with url: "#", class: "identification__form" do |f|
      %div
        %p
          お客さまの本人情報をご登録ください。
          %br
          登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        %p.identification__form__text-right
          = link_to '#' do
            本人確認書類のアップロードについて
            = fa_icon "chevron-right"

      .identification__form__form-group
        %label
          お名前
        %p
          浦島 太朗

      .identification__form__form-group
        %label
          お名前カナ
        %p
          ウラシマ タロウ

      .identification__form__form-group
        %label
          生年月日
        %p
          1999/9/9

      .identification__form__form-group
        %label
          郵便番号
        %span.identification__form__form-group__form-arbitrary
          任意
        = f.text_field :zipcode, {placeholder: "例) 1234567", class: "identification__form__form-group__input-default"}

      .identification__form__form-group
        %label
          都道府県
        %span.identification__form__form-group__form-arbitrary
          任意
        .identification__form__form-group__select-wrap
          = fa_icon "chevron-down"
          = f.select :prefecture, [["--", ""], ["北海道", "北海道"]], {}, {class: "identification__form__form-group__select-default"}

      .identification__form__form-group
        %label
          市区町村
        %span.identification__form__form-group__form-arbitrary
          任意
        = f.text_field :city, {placeholder: "例) 竜宮市亀区", class: "identification__form__form-group__input-default"}

      .identification__form__form-group
        %label
          番地
        %span.identification__form__form-group__form-arbitrary
          任意
        = f.text_field :house_address, {placeholder: "例) 竜宮城1-1-1", class: "identification__form__form-group__input-default"}

      .identification__form__form-group
        %label
          建物名
        %span.identification__form__form-group__form-arbitrary
          任意
        = f.text_field :building_name, {placeholder: "例) 玉手箱ビルディング 102号", class: "identification__form__form-group__input-default"}

      = f.submit '登録する', class: "identification__form__submit"

      .identification__form__form-group.identification__form__text-right
        = link_to '#' do
          本人情報の登録について
          = fa_icon "chevron-right"

  = render 'items/footer_btn'

= render 'items/footer'

app/views/users/logout.html.haml
= render 'items/header_guide'

%main.mypage-container.clearfix

  .content
    %section.logout__container
      = form_with url: root_path, method: :post, class: 'logout__form' do |f|
        .logout__content
          = f.button "ログアウト", type: 'submit', class: 'logout__submit'

  = render 'users/mypage/side'
  = render 'items/footer_btn'

= render 'items/footer'

app/views/users/profile.html.haml
- breadcrumb :profile
= render 'items/header_guide'
= render 'shared/breadcrumbs'
%main.mypage-container.clearfix
  = render 'users/mypage/side'

  .profile
    .profile__contener
      %h2.bold プロフィール
    = form_with url: '#', class: 'profile__greeting' do |f|
      .profile__greeting
        .profile__greeting__icon
          %figure
            = image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbM5lmk9ySlH6e3nKSxCUsmKEkIxPwsPIFuvDikBpe-I2pSSNQ")
          = f.text_field :nickname ,value:"テックエキスパー子", placeholder:"(例)AYA★セール中", class:"input-box"

      .profile__sentence
        = f.text_area :introduction,placeholder: "例）こんにちは☆ テックエキスパー子です！ピンク中心に出品しています。楽しくプログラミングできるように心がけています。お気軽にどうぞ♪"

        .profile__sentence__change_content
          = button_tag "変更する",type: 'submit', class: 'btn-default'

  = render 'items/footer_btn'

= render 'items/footer'

app/views/users/profile_edit.html.haml
= render 'items/header_guide'

%main.mypage-container.clearfix
  = render 'users/mypage/side'

  .profile
    .profile__contener
      %h2.bold プロフィール
    = form_with url: '#', class: 'profile__greeting' do |f|
      .profile__greeting
        .profile__greeting__icon
          %figure
            = image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbM5lmk9ySlH6e3nKSxCUsmKEkIxPwsPIFuvDikBpe-I2pSSNQ")
          = f.text_field :nickname ,value:"テックエキスパー子", placeholder:"(例)AYA★セール中", class:"input-box"

      .profile__sentence
        = f.text_area :introduction,placeholder: "例）こんにちは☆ テックエキスパー子です！ピンク中心に出品しています。楽しくプログラミングできるように心がけています。お気軽にどうぞ♪"

        .profile__sentence__change_content
          = button_tag "変更する",type: 'submit', class: 'btn-default'

  = render 'items/footer_btn'

= render 'items/footer'

app/views/users/show.html.haml
- if current_page?(user_path(current_user))
  - breadcrumb :mypage
- else
  - breadcrumb :user, @user

= render 'items/header_guide'
= render 'shared/breadcrumbs'

- if current_page?(user_path(current_user))
  %main.mypage-container.clearfix
    = render 'users/mypage/content'
    = render 'users/mypage/side'
    = render 'items/footer_btn'
- else
  = render @user

= render 'items/footer'