config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    # ログイン及びログアウト
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#sign_out"
    delete "sign_out", to: "users/sessions#destroy"

    # 新規登録画面
    get "sign_up/top", to: "users/registrations#top"
    get "sign_up", to: "users/registrations#new"
    post "sign_up", to: "users/registrations#create"
    get "sign_up/sms_authorization", to: "users/registrations#sms_authorization"
    get "sign_up/deliver_address", to: "users/registrations#deliver_address"
    post "sign_up/deliver_address", to: "users/registrations#deliver_address_create"
    get "sign_up/credit_card", to: "users/registrations#credit_card"
    get "sign_up/finish", to: "users/registrations#finish"
  end

  # 商品画面
  resources :items, only: [:index, :new, :edit, :update, :show, :destroy, :create] do   # createは消す # 商品出品とコンフリクトするかも
    post "likes", to: "item_likes#create"
    delete "likes", to: "item_likes#destroy"
    resources :trades, only: [:new, :create]
    member do
      get :mypage_item_show   # マイページから出品した商品の詳細を表示するためのルーティング
    end
  end

  resources :users, only: [:show, :create] do
    # クレジットカード
    resource :credit_card, except: [:edit, :update], module: :users
    # お届け先住所
    resource :deliver_address, except: [:edit, :destroy], module: :users
    
    member do
      get :profile
      get :identification

      scope 'listings', module: :users, controller: 'listings' do
        get :listing
        get :in_progress
        get :completed
      end
    end
  end

  # カテゴリ
  resources :categories, only: [:index, :show]
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  include Scopes
  include Commentable

  enum condition: [:unused, :almost_new, :non_dirty, :little_dirty, :dirty, :bad]
  enum task: [:exhibiting, :waiting_shipping, :rating_seller, :rating_buyer, :complete, :stopping]
  enum payer_delivery_expense: [:seller_burden, :buyer_burden]
  enum shipping_method: [:undecided, :easy_mercari_post, :yu_mail, :letter_pack, :regular_mail, :yamato, :yu_pack, :click_post, :yu_packet]
  enum delivery_days: [:within1_2days, :within2_3days, :within4_7days]

  belongs_to :user
  has_many :item_images, dependent: :destroy
  has_many :item_likes
  has_many :liked_users, through: :items_likes, source: :user
  belongs_to_active_hash :prefecture
  belongs_to :category
  belongs_to :size

  accepts_nested_attributes_for :item_images

  with_options presence: true do
    validates :name
    validates :price
    validates :description
    validates :condition
    validates :task
    validates :shipping_method
    validates :delivery_days
    validates :prefecture
    validates :payer_delivery_expense
  end
  has_one :trade

  scope :category_items, -> (category_id) { where(category_id: category_id) }

  # MEMO: scopeがnilを返す場合は検索対象のモデルのallが適用されるためクラスメソッドで記述
  def self.prev_item(item)
    recently.where('created_at <= ? and id < ?', item.created_at, item.id).first
  end

  # MEMO: scopeがnilを返す場合は検索対象のモデルのallが適用されるためクラスメソッドで記述
  def self.next_item(item)
    recently.where('created_at >= ? and id > ?', item.created_at, item.id).last
  end

  def after_first_categories
    category.path.slice(1..-1)
  end

  def delimited_price
    price.to_s(:delimited)
  end

  def user_other_items
    user.items.includes(:item_images).recently.where.not(id: self.id)
  end

  def category_other_items
    category.items.includes(:item_images).recently.where.not(id: self.id)
  end

  def liked_by?(user)
    item_likes.where(user_id: user).present?
  end

  def seller?(target_user)
    unless target_user.nil?
      user.id == target_user.id
    else
      false
    end
  end

  validates :name,
            :price,
            :description,
            :condition,
            :task,
            :payer_delivery_expense,
            :shipping_method,
            :delivery_days,
            :user_id,
            :category_id,
            :size_id,
            :prefecture_id,
            presence: true

  validate :item_images_exist


  def item_images_exist
    errors.add(:item_images, "を選択してください") if item_images.blank?
  end
  def trading?
    task.include?('waiting_shipping') || task.include?('rating_seller') || task.include?('rating_buyer')
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :mypage_item_show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    # 一旦、保留
    # root_categories = Category.where(ancestry: nil)
    # @categories = []
    # root_categories.each do |category|
    #   @categories.push({category: category, count: category.belongs_items.count})
    # end
    # @categories = @categories.sort_by {|a| -a[:count]}.map { |obj| obj[:category] }.take(4)

    @categories = Category.roots.limit(4)
  end

  def search
    @items = []
  end

  def show
    # 一旦、保留
    # @item_comment = ItemComment.new
    # @item_comments = @item.item_comments
  end

  def new
    @item = Item.new
    @item.item_images.build
  end

  def create
    @item = Item.new(item_params)
      if params[:item][:item_images_attributes] && @item.save
        redirect_to root_path
      else
        render :new
      end
  end

  def mypage_item_show
    check_my_item
  end

  def edit
    check_my_item
    @item.item_images.build
    @parents = Category.all.order("id ASC").limit(13)
    gon.item_images = @item.item_images       # 保存されている画像の配列変数をjavascriptで使えるようにする
  end

  def update
    delete_image_ids = delete_image_id_params[:delete_image_id]

    if delete_image_ids && delete_image_ids.length == @item.item_images.length
      @error = "画像がありません"
      render :edit
    elsif @item.update(item_params)
      if delete_image_ids
        delete_image_ids.each do |id|
          ItemImage.find(id).destroy
        end
      end
      redirect_to action: 'mypage_item_show'
    else
      render :edit
    end

  end

  def destroy
    @item.destroy
    redirect_to listing_user_url(current_user)
  end

  private
  def set_item
    @item = Item.find(params[:id]).decorate
  end

  def item_params
    params.require(:item).permit(:name,
                                  :price,
                                  :description,
                                  :condition,
                                  :task,
                                  :payer_delivery_expense,
                                  :delivery_days,
                                  :shipping_method,
                                  :category_id,
                                  :size_id,
                                  :prefecture_id,
                                  item_images_attributes:[:id, :image, :item_id]
    ).merge(user_id: current_user.id)
  end

  def delete_image_id_params
    params.permit(delete_image_id:[])
  end

  def check_my_item
    # 表示しようとしているitemが、ログイン中ユーザーが出品したitemではない場合、マイページにリダイレクト
    if @item.user_id != current_user.id
      redirect_to controller: 'users', action: 'show', id: current_user.id
      return
    end
  end

end

app/helpers/items_helper.rb
module ItemsHelper
  # TODO: 別ウィンドウで開くようにする
  def facebook_link(instance)
    if instance.is_a?(Item)
      link_to "http://www.facebook.com/share.php?u=#{CGI.escape(url_for(only_path: false))}", target: :_blank, class: 'detail-item__sns--button' do
        content_tag :i, nil, class: 'icon-facebook'
      end
    elsif instance.is_a?(User)
      link_to "http://www.facebook.com/share.php?u=#{CGI.escape(url_for(only_path: false))}", target: :_blank, class: 'detail-user__sns--button' do
        content_tag :i, nil, class: 'icon-facebook'
      end
    end
  end
  
  # TODO: 別ウィンドウで開くようにする
  def twitter_link(instance)
    if instance.is_a?(Item)
      text = "#{instance.name}… (¥#{instance.price.to_s(:delimited)}) #{url_for(only_path: false)} フリマアプリ「freemarket_sample_53a」で販売中♪ #freemarket_sample_53a @freemarket_sample_53aさんから"
    elsif instance.is_a?(User)
      text = "フリマアプリ「メルカリ」で販売しています #{url_for(only_path: false)} #freemarket_sample_53a @freemarket_sample_53aさんから"
    end
    link_to "http://twitter.com/share?count=horizontal&original_referer=#{CGI.escape(url_for(only_path: false))}&text=#{CGI.escape(text)}", class: 'detail-item__sns--button', target: :_blank do
      content_tag :i, nil, class: 'icon-twitter'
    end
  end

  # TODO: 別ウィンドウで開くようにする
  def pinterest_link(instance)
    if instance.is_a?(Item)
      url = CGI.escape(url_for(only_path: false))
      media = CGI.escape(instance.item_images.first.image.url)
      description = CGI.escape("freemarket_sample_53a: #{instance.name} #freemarket_sample_53a")
    elsif instance.is_a?(User)
      return
    end
    link_to "http://pinterest.com/pin/create/button/?url=#{url}&media=#{media}&description=#{description}", class: 'detail-item__sns--button', target: :_blank do
      content_tag :i, nil, class: 'icon-pinterest'
    end
  end

  def direction_item(direction, item)
    direction_item = eval("Item.#{direction}_item(item)")
    icon_class_name = direction.include?('prev') ? "icon-arrow-left" : "icon-arrow-right"

    if direction_item.present?
      link_to item_path(direction_item) do
        concat direction_item.name
        concat content_tag(:i, nil, class: icon_class_name)
      end
    end
  end

  def payer_delivery_expense_explanation(select)
    select = Item.payer_delivery_expenses_i18n.invert
    return_hash = {}
    select.each{|key, value|
      if select.invert[value] == Item.payer_delivery_expenses_i18n[:seller_burden]
        return_hash[select.invert[value] += "(出品者負担)"] = select[key]
      elsif select.invert[value] == Item.payer_delivery_expenses_i18n[:buyer_burden]
        return_hash[select.invert[value] += "(購入者負担)"] = select[key]
      else
      end
    }
    return return_hash
  end

end

app/views/items/_category.html.haml
.recommended
  .main
    .main__box
      .main__slideshow
        .main__slideshow__frame
          %ul.main__slideshow__list
            = image_tag"/top-banner-autumn-fes.jpg"
            = image_tag"/top-banner-camp.jpg"
            = image_tag"/top-banner-super-exhibition-fes.jpg"
            = image_tag"/top-banner-enari-fes.jpg"

            %li.main__slideshow__list__slide
              = link_to root_path do
                .active
        .main__slideshow__left
          .main__slideshow__left__box

        .main__slideshow__right
          .main__slideshow__right__box

        .main__slideshow__button
          .main__slideshow__button__box
            %span
            %span
            %span

  .main__category
    %h2 人気のカテゴリー
    .main__category__Heading
      %ul.main__category__Heading__list
        %li
          = link_to "レディース",'#1'
        %li
          = link_to "メンズ",'#2'
        %li
          = link_to "ベビー・キッズ",'#3'
        %li
          = link_to "インテリア・住まい・小物",'#4'

  .main__product
    - @categories.limit(4).each do |category| 
      .main__product__contener
        .main__product__contener__name{id: category.id}
          %h3=category.name
          = link_to "もっと見る ", root_path, class:"more_see"

        .main__collection
          .main__collection__box
            - Item.category_items(category.indirects.ids).recently.limit(10).each do |item| 
              .main__collection__box__parts
                = link_to item_path(item.id),nil do
                  %figure
                    %figcaption
                      %span
                        = item.name if item.name.present?
                    .main__collection__box__parts__img
                      %span
                        ¥
                        = item.price if item.price.present?
                      = image_tag(item.item_images[0].image.url) if item.item_images.present?

app/views/items/_detail-item-messagebox.html.haml
-# TODO:余裕があれば実装
-# .detail-item__messages
-#   - @item.item_comments.each do |comment|
-#     .detail-item__message
-#       = link_to item_path, class: 'detail-item__message__user-icon' do
-#         %div
-#           -# TODO:アバターモデル追加
-#           = image_tag '/message_icon.jpg'
-#           %span.bold
-#             = @comment.user.nickname
-#       .detail-item__message__body
-#         .detail-item__message__body--text<>
-#           = @comment.content
-#         .detail-item__message__body__icons
-#           .detail-item__message__body__icons--left
-#             %i.icon-clock
-#             %span="39分前"
-#           .detail-item__message__body__icons--right
-#             = form_with url: item_path do
-#               = button_tag type: :submit do
-#                 %i.icon-flag 
-#         %i.icon-balloon

-# TODO: 余裕があれば実装
.detail-item__input-message
  = form_with url: item_path, method: :post, class: 'detail-item__input-message__form' do |f|
    %p="相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。"
    = f.text_area :body, class: 'detail-item__input-message__textarea'
    = f.button nil, type: 'submit', class: 'detail-item__input-message__submit detail-item__input-message__submit--btn-gray' do
      %span="コメントする"

app/views/items/_footer_btn.html.haml
.footer-exhibit-btn
  =link_to new_item_path, class: "sell-link" do
    .sell-link__box
      .sell-link__box__font 出品
      %svg.sell-link__box__icon{"aria-hidden": "true", height: "16", viewbox: "0 0 18 16", width: "18"}
        %path{d: "M6.3 0L4.653 1.778H1.8c-.99 0-1.8.8-1.8 1.778v10.666C0 15.2.81 16 1.8 16h14.4c.99 0 1.8-.8 1.8-1.778V3.556c0-.978-.81-1.778-1.8-1.778h-2.853L11.7 0H6.3zM9 13.333c-2.484 0-4.5-1.99-4.5-4.444 0-2.453 2.016-4.445 4.5-4.445s4.5 1.992 4.5 4.445c0 2.453-2.016 4.444-4.5 4.444zm0-1.6c1.59 0 2.88-1.273 2.88-2.844S10.59 6.044 9 6.044c-1.59 0-2.88 1.274-2.88 2.845 0 1.57 1.29 2.844 2.88 2.844z", fill: "currentColor", "fill-rule": "nonzero"}

app/views/items/_header_guide.html.haml
%header.mercari-header
  .mercari-top
    .topmein-search-band

      .topmein-mercari
        = link_to root_path ,class: "topmein-mercari__box" do
          = image_tag("/logo.svg",alt: "Mercari",class:"topmein-mercari__box__icon")


      = form_with url: root_path, class: 'topmein-search-form' do |f|
        = f.search_field :keyword, {name: "keyword", class: "topmein-search-form__write", placeholder: '何かお探しですか？', value: ""}
        = f.button "", class: "topmein-search-form__button" do
          %svg.topmein-search-form__button__icon{"aria-hidden": "true", height: "16", viewbox: "0 0 16 16", width: "16"}
            %path{d: "M11.435 10.063h-.723l-.256-.247a5.92 5.92 0 0 0 1.437-3.87 5.946 5.946 0 1 0-5.947 5.947 5.92 5.92 0 0 0 3.87-1.437l.247.256v.723L14.637 16 16 14.637l-4.565-4.574zm-5.489 0A4.111 4.111 0 0 1 1.83 5.946 4.111 4.111 0 0 1 5.946 1.83a4.111 4.111 0 0 1 4.117 4.116 4.111 4.111 0 0 1-4.117 4.117z", fill: "currentColor", "fill-rule": "nonzero"}

    .topmein-select-band
      .topmein-select-band__left
        %ul.topmein-select-band__left__category.ddmenu
          %li
            =link_to categories_path, class: "topmein-select-band__left__category__tag" do
              %svg.topmein-select-band__left__category__tag__search{"aria-hidden": "true", height: "16", viewbox: "0 0 20 16", width: "20"}
                %path{d: "M18.799 15.25h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zm0-6h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zm0-6h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zM2 16a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0-6a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0-6a2 2 0 1 0 0-4 2 2 0 0 0 0 4z", fill: "currentColor", "fill-rule": "nonzero"}
              カテゴリーから探す
            %ul.ddmenu--top-level
              - ddmenu_list(Category.roots)

        .topmein-select-band__left__category
          = link_to root_path , class: "topmein-select-band__left__category__tag" do
            %svg.topmein-select-band__left__category__tag__bland{"aria-hidden": "true", height: "16", viewbox: "0 0 23 16", width: "23"}>
              %path{d: "M6.315 0L4.473 1.806 2.833.019.73 1.977l1.69 1.84L1.198 5.02c-1.594 1.594-1.594 4.188-.01 5.772L6.3 16h13.272a3.08 3.08 0 0 0 3.077-3.077V3.076A3.08 3.08 0 0 0 19.57 0H6.315zm13.46 12.925a.211.211 0 0 1-.205.205H7.504L3.227 8.771a1.226 1.226 0 0 1-.01-1.71L4.38 5.92l1.28 1.371a2.68 2.68 0 1 0 2.13-1.93L6.433 3.907 7.49 2.87h12.082a.211.211 0 0 1 .206.205v9.848h-.002z", fill: "currentColor", "fill-rule": "nonzero"}
            ブランドから探す


      %ul.topmein-select-band__right
        - if user_signed_in?
          %li.topmein-select-band__right__command
            = link_to root_path , class: "topmein-select-band__right__command__box" do
              %svg.topmein-select-band__right__command__box__menu{"aria-hidden": "true", height: "16", viewbox: "0 0 14 16", width: "14"}
                %path{d: "M6.592 16c.89 0 1.632-.734 1.632-1.632H4.928c0 .898.742 1.632 1.664 1.632zm4.896-4.928V6.976c-.008-2.521-1.345-4.63-3.712-5.184v-.576C7.79.55 7.241 0 6.56 0c-.68 0-1.23.55-1.216 1.216v.576c-2.36.554-3.704 2.654-3.712 5.184v4.096L0 12.704v.832h13.12v-.832l-1.632-1.632zm-1.632.832h-6.56V6.976c0-2.024 1.238-3.68 3.296-3.68 2.026 0 3.264 1.656 3.264 3.68v4.928z", fill: "currentColor", "fill-rule": "nonzero"}
              お知らせ
              %span.topmein-select-band__right__command__box__icon
                1
          %li.topmein-select-band__right__command
            = link_to root_path , class: "topmein-select-band__right__command__box" do
              %svg.topmein-select-band__right__command__box__mark{"aria-hidden": "true", height: "16", viewbox: "0 0 21 16", width: "21"}
                %path{d: "M6.682 12.657L1.67 7.642 0 9.313 6.682 16 21 1.672 19.33 0z", fill: "currentColor", "fill-rule": "nonzero"}
              やることリスト
              %span.topmein-select-band__right__command__box__icon
                4
          %ul.topmein-select-band__right__command.ddmenu__mypage
            %li
              = link_to current_user , class: "topmein-select-band__right__command__box" do
                = image_tag("/member_photo_noimage_thumb.png", alt: "", class: "topmein-select-band__right__command__box__mypage")
                マイページ
              %ul
                %li.mypage__list__top
                  .mypage__list__top__background
                    = image_tag "/sample-avatar.jpg", height: '60', width: '60'
                  .mypage__list__top__username
                    %span=current_user.full_name
                  .mypage__list__top__userinfo
                    %span="評価: #{current_user.user_reviews.count}"
                    %span="出品数: #{current_user.items.count}"

                %li
                  = link_to current_user do
                    %span="いいね!一覧"
                    %i.icon-arrow-right
                %li
                  =link_to listing_user_path(current_user) do
                    %span="出品した商品 - 出品中"
                    %i.icon-arrow-right
                %li
                  =link_to in_progress_user_path(current_user) do
                    %span="出品した商品 - 取引中"
                    %i.icon-arrow-right
                %li
                  =link_to completed_user_path(current_user) do
                    %span="出品した商品 - 売却済み"
                    %i.icon-arrow-right
                %li
                  =link_to current_user do
                    %span="購入した商品 - 取引中"
                    %i.icon-arrow-right
                %li
                  =link_to current_user do
                    %span="購入した商品 - 過去の取引"
                    %i.icon-arrow-right

        - else
          %li.topmein-select-band__right__command__box--new
            = link_to "新規会員登録", sign_up_top_path
          %li.topmein-select-band__right__command__box--login
            = link_to "ログイン", sign_in_path


-# 以下コメントアウトはログイン前のheaderのviewとして記述しています。
-# まだrenderで分けれていない状態なので下にコメントアウトしております。
-#       .topmein-select-band__user
-#         .topmein-select-band__user__signin
-#           =link_to root_path , class: "topmein-select-band__user__signin__box" do
-#             新規会員登録

-#           =link_to root_path , class: "topmein-select-band__user__logout__box" do
-#             ログイン

app/views/items/_logo-footer.html.haml
%footer.logo-footer
  %nav
    %ul
      %li
        = link_to root_path do
          プライバシーポリシー
      %li
        = link_to root_path do
          メルカリ利用規約
      %li
        = link_to root_path do
          特定商取引に関する表記

  = link_to root_path, class: "logo-footer__logo" do
    = image_tag '/logo-gray.svg', alt: 'mercari', height: '65', width: '80'

  %p
    %small &copy; 2019 freemarket_sample_53a

app/views/items/_logo-header.html.haml
%header.logo-header
  %h1
    = link_to root_path do
      = image_tag '/logo.svg', alt: 'mercari'

app/views/items/index.html.haml
= render 'items/header_guide';

.recommended
  .main
    .main__box
      .main__slideshow
        .main__slideshow__frame
          %ul.main__slideshow__list
            = image_tag"/top-banner-autumn-fes.jpg"
            = image_tag"/top-banner-camp.jpg"
            = image_tag"/top-banner-super-exhibition-fes.jpg"
            = image_tag"/top-banner-enari-fes.jpg"

            %li.main__slideshow__list__slide
              = link_to root_path do
                .active
        .main__slideshow__left
          .main__slideshow__left__box

        .main__slideshow__right
          .main__slideshow__right__box

        .main__slideshow__button
          .main__slideshow__button__box
            %span
            %span
            %span

  .main__category
    %h2 人気のカテゴリー
    .main__category__Heading
      %ul.main__category__Heading__list
        - @categories.each do |category|
          %li= link_to category.name,"##{category.id}"

  .main__product
    = render partial: @categories, locals: { limit: 10 }

= render 'items/footer';
= render 'items/footer_btn';

app/views/items/mypage_item_show.html.haml
= render 'items/header_guide'
.detail-item
  - if /waiting_shipping|rating_seller|rating_buyer/ =~ @item.task
    %span.detail-item__mypage-item-show__task.detail-item__mypage-item-show__task--state=@item.task_i18n
  - else
    %span.detail-item__mypage-item-show__task=@item.task_i18n

  = render partial: 'items/detail-item-top', locals: { item: @item }

  .detail-item__description
    .detail-item__description__inner<>
      = @item.description

.detail-item__message-box
  .detail-item__messages
    = link_to '商品の編集', edit_item_path(@item), class: 'detail-item__edit'
    %p.text-center or
    = link_to '出品を一旦停止する', "#", method: :delete, class: 'detail-item__delete'
    = link_to 'この商品を削除する', item_path(@item), method: :delete, class: 'detail-item__delete'

.detail-item__message-box
  = render 'items/detail-item-messagebox'

= render 'items/footer'

app/views/items/show.html.haml
= render 'items/header_guide'

.detail-item
  = render partial: 'items/detail-item-top', locals: { item: @item }

  - if @item.seller?(current_user)
    = link_to '出品した商品です', "javascript:void(0)", class: 'detail-item__buy detail-item__buy--not-allowed'
  - elsif @item.trading?
    = link_to '取引中です', "javascript:void(0)", class: 'detail-item__buy detail-item__buy--not-allowed'
  - elsif @item.task.include?('complete')
    = link_to '売り切れました', "javascript:void(0)", class: 'detail-item__buy detail-item__buy--not-allowed'
  - elsif @item.task.include?('stopping')
    = link_to '出品停止中です', "javascript:void(0)", class: 'detail-item__buy detail-item__buy--not-allowed'
  - else
    = link_to '購入画面に進む', new_item_trade_path(@item), class: 'detail-item__buy'

  .detail-item__description
    .detail-item__description__inner<>
      = @item.description

  .detail-item__links
    .detail-item__links--left

      - if @item.seller?(current_user)
        = link_to "javascript:void(0)", { class: "detail-item__links__btn--like detail-item__links__btn not-allowed"} do
          %i.icon-like.fa
          %span="いいね!"
          %span=@item.item_likes.count

      - else

        - if @item.liked_by?(current_user)
          = link_to item_likes_path(@item), { class: "detail-item__links__btn--like detail-item__links__btn active", method: :delete, remote: true } do
            %i.icon-like.fa
            %span="いいね!"
            %span=@item.item_likes.count

        - else
          = link_to item_likes_path(@item), { class: "detail-item__links__btn--like detail-item__links__btn", method: :post, remote: true } do
            %i.icon-like.fa
            %span="いいね!"
            %span=@item.item_likes.count

      = link_to item_path, data: {open: "modal"}, class: "detail-item__links__btn detail-item__links__btn--report" do
        %i.icon-flag
        %span="不適切な商品の報告"

    .detail-item__links--right
      = link_to item_path, target: :_blank do
        %i.icon-lock
        %span="あんしん・あんぜんへの取り組み"


.detail-item__message-box
  = render 'items/detail-item-messagebox'

%ul.detail-item__nav
  %li.detail-item__nav--prev
    = direction_item('prev', @item)
  %li.detail-item__nav--next
    = direction_item('next', @item)


.detail-item__sns
  .detail-item__sns--facebook
    = facebook_link(@item)

  .detail-item__sns--twitter
    = twitter_link(@item)

  .detail-item__sns--pinterest
    = pinterest_link(@item)


.detail-item__other-items
  .detail-item__other-items--users
    %h2.detail-item__other-items--title
      = link_to "#{@item.user.nickname}さんのその他の出品", user_path(@item.user)

    .detail-item__other-items__contents
      - @item.user_other_items.limit(6).each do |item|
        .detail-item__other-items__content
          = link_to item_path(item), nil do
            - if item.task.include?('complete')
              = render 'shared/soldout'
            %figure.detail-item__other-items__content--figure
              - if item.item_images.present?
                = image_tag item.item_images.first.image.url, class: "lazyloaded"
              - else 
                = image_tag('/not_found.png')
            .detail-item__other-items__content__box
              %h3.detail-item__other-items__content__box--title.font-2=item.name
              .detail-item__other-items__content__box--footer
                .detail-item__other-items__content__box--price.font-5="¥#{item.delimited_price}"
                .detail-item__other-items__content__box--like.font-2
                  %i.icon-like
                  %span=item.item_likes.count

  .detail-item__other-items--brand-category
    %h2.detail-item__other-items--title
      = link_to "#{@item.category.name} (#{@item.category.root.name}) その他の出品", category_path(@item.category)

    .detail-item__other-items__contents
      - @item.category_other_items.limit(6).each do |item|
        .detail-item__other-items__content
          = link_to item_path(item), nil do
            - if item.task.include?('complete')
              = render 'shared/soldout'
            %figure.detail-item__other-items__content--figure
              - if item.item_images.present?
                = image_tag item.item_images.first.image.url, class: "lazyloaded"
              - else
                = image_tag('/not_found.png')
            .detail-item__other-items__content__box
              %h3.detail-item__other-items__content__box--title.font-2=item.name
              .detail-item__other-items__content__box--footer
                .detail-item__other-items__content__box--price.font-5="¥#{item.delimited_price}"
                .detail-item__other-items__content__box--like.font-2
                  %i.icon-like
                  %span=item.item_likes.count


.detail-item__bread-crumbs
  %ul
    %li
      = link_to 'メルカリ', root_path
      %i.icon-arrow-right
    %li
      %span.detail-item__bread-crumbs--title=@item.name

= render 'items/footer'